// <auto-generated />
using System;
using Blog.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.DATA.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20230110231424_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blog.DATA.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İş Dünyası"
                        });
                });

            modelBuilder.Entity("Blog.DATA.Despatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Despatches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7342),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7329),
                            Title = "Text Example 0"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7407),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7406),
                            Title = "Text Example 1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7415),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7414),
                            Title = "Text Example 2"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7421),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7420),
                            Title = "Text Example 3"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7427),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7426),
                            Title = "Text Example 4"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7433),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7432),
                            Title = "Text Example 5"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7439),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7438),
                            Title = "Text Example 6"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7445),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7444),
                            Title = "Text Example 7"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7452),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7451),
                            Title = "Text Example 8"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7457),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7456),
                            Title = "Text Example 9"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7463),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7462),
                            Title = "Text Example 10"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7470),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7469),
                            Title = "Text Example 11"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7476),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7475),
                            Title = "Text Example 12"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7483),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7482),
                            Title = "Text Example 13"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7489),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7488),
                            Title = "Text Example 14"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7496),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7495),
                            Title = "Text Example 15"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7525),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7524),
                            Title = "Text Example 16"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7532),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7531),
                            Title = "Text Example 17"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7538),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7537),
                            Title = "Text Example 18"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7545),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7543),
                            Title = "Text Example 19"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7550),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7549),
                            Title = "Text Example 20"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7556),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7555),
                            Title = "Text Example 21"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7564),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7563),
                            Title = "Text Example 22"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7569),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7569),
                            Title = "Text Example 23"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7575),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7574),
                            Title = "Text Example 24"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7582),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7580),
                            Title = "Text Example 25"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7588),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7587),
                            Title = "Text Example 26"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7593),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7592),
                            Title = "Text Example 27"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7599),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7598),
                            Title = "Text Example 28"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7605),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7604),
                            Title = "Text Example 29"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7611),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7610),
                            Title = "Text Example 30"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7617),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7616),
                            Title = "Text Example 31"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7623),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7622),
                            Title = "Text Example 32"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7629),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7628),
                            Title = "Text Example 33"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7634),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7633),
                            Title = "Text Example 34"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7639),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7639),
                            Title = "Text Example 35"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7645),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7644),
                            Title = "Text Example 36"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7650),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7649),
                            Title = "Text Example 37"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7656),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7655),
                            Title = "Text Example 38"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7661),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7660),
                            Title = "Text Example 39"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7667),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7666),
                            Title = "Text Example 40"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7673),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7672),
                            Title = "Text Example 41"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7679),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7678),
                            Title = "Text Example 42"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7686),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7686),
                            Title = "Text Example 43"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7692),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7691),
                            Title = "Text Example 44"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7697),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7696),
                            Title = "Text Example 45"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7703),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7702),
                            Title = "Text Example 46"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            ChangedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7709),
                            Content = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            CreatedDate = new DateTime(2023, 1, 11, 2, 14, 23, 583, DateTimeKind.Local).AddTicks(7708),
                            Title = "Text Example 47"
                        });
                });

            modelBuilder.Entity("Blog.DATA.Despatch", b =>
                {
                    b.HasOne("Blog.DATA.Category", "Category")
                        .WithMany("Despatches")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Blog.DATA.Category", b =>
                {
                    b.Navigation("Despatches");
                });
#pragma warning restore 612, 618
        }
    }
}
